@host = http://localhost:5035
@token = eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJzdWIiOiIxIiwicGxheWVySWQiOiIxIiwidW5pcXVlX25hbWUiOiJzZXR0IiwianRpIjoiNmJkNWFiNDAtYmZiMi00ODU0LWE0MjAtNTYxYmFiYTk1NGZjIiwibmJmIjoxNzg2NDc4MzIxLCJleHAiOjE3ODY0ODE5MjEsImlzcyI6Ik11bHRpcGxheWVyQmFja2VuZC5BcGkiLCJhdWQiOiJNdWx0aXBsYXllckJhY2tlbmQuQ2xpZW50In0.HuTbqhJwzDz_We0NjIQ3dtsCtYdEFXPVOHtSev9zjsU
#@token = eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJzdWIiOiIyIiwicGxheWVySWQiOiIyIiwidW5pcXVlX25hbWUiOiJhbGljZSIsImp0aSI6ImU5N2E3MzE2LTQ1ZTAtNDdmNS1hZjRjLTg3YzAwN2JmZWVmYiIsIm5iZiI6MTc4NjQ4MTE5OSwiZXhwIjoxNzg2NDg0Nzk5LCJpc3MiOiJNdWx0aXBsYXllckJhY2tlbmQuQXBpIiwiYXVkIjoiTXVsdGlwbGF5ZXJCYWNrZW5kLkNsaWVudCJ9.ovB4ETpSzJuX-IjRUQ9ES-X2nUERNAK2gyKcVvQtas4
### My profile
GET {{host}}/api/players/me
Authorization: Bearer {{token}}

### My inventory
GET {{host}}/api/players/me/inventory
Authorization: Bearer {{token}}

### Add item to my inventory
POST {{host}}/api/players/me/inventory
Authorization: Bearer {{token}}
Content-Type: application/json

{
  "itemName": "Health Potion",
  "amount": 10
}